let gamecards = [
  // order od right/left/ButtonEffect is [stress, health, social, study]
  {
    title: "Classes stopped at 19h What should I do next?",
    lefttext: "Keep studying until midnight",
    rigthtext: "Go play online videogames",
    rightButtonEffect: [-5, 0, 5, -10],
    leftButtonEffect: [5, 0, -5, 10],
  },
  {
    title: "Woke up early still have time before classes start",
    lefttext: "Go for a walk",
    rigthtext: "Study the contend prior to classes",
    rightButtonEffect: [5, 0, 0, 5],
    leftButtonEffect: [-5, 5, 0, 0],
  },
  {
    title: "It is sunday what should I do today?",
    lefttext: "Study harder!",
    rigthtext: "Forget your problems, Carpe Dien",
    rightButtonEffect: [-10, 5, 5, -10],
    leftButtonEffect: [10, -5, -5, 10],
  },
  {
    title: "Arrrghh another kata :(",
    lefttext: "Pull-stacker copy from Google",
    rigthtext: "Work hard and solve it",
    rightButtonEffect: [5, 0, 0, 10],
    leftButtonEffect: [0, 0, 0, -5],
  },
  {
    title: "Today lab is here! Wow such clever! Nice!",
    lefttext: "I will finish now!!!!!",
    rigthtext: "The bonus interations are not that important",
    rightButtonEffect: [10, -5, -10, 15],
    leftButtonEffect: [20, -10, -15, 20],
  },
  {
    title: "Wait there are self guided content??? Jesus!!!!",
    lefttext: "Sure I need to learn everything!!!!",
    rigthtext: "Perhaps no one will no if I skipped",
    rightButtonEffect: [0, 0, 0, -5],
    leftButtonEffect: [5, 0, 0, 5],
  },
  {
    title: "Need to clear my head!",
    lefttext: "Just die on a couch",
    rigthtext: "Go for a run",
    rightButtonEffect: [-5, 10, 0, 0],
    leftButtonEffect: [-5, -10, 0, 0],
  },
  {
    title: "Urra! I was just invated for a party during the week",
    lefttext: "Got wasted",
    rigthtext: " I have to study",
    rightButtonEffect: [0, 0, -10, 5],
    leftButtonEffect: [-20, -20, 20, -20],
  },
  {
    title: "Look there is a fly on my desk!",
    lefttext: "Pass one hour staring it",
    rigthtext: "Shuh, fly away little fly",
    rightButtonEffect: [5, 0, 0, 5],
    leftButtonEffect: [-5, 0, 0, -5],
  },
  {
    title: "Have no time to cook :/ i will order:",
    lefttext: "Junk Food!!!!",
    rigthtext: "A sad salad :(",
    rightButtonEffect: [0, 5, 0, 0],
    leftButtonEffect: [-5, -10, 0, 0],
  },
];
